# Generated by Django on 2026-01-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_userproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=10, null=True, blank=True),
        ),
    ]
